// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUfTP49kUziS15Pdc6B9XfR5eI6D_gPk',
    appId: '1:230882435362:web:cedee98dee660b1cb0c57b',
    messagingSenderId: '230882435362',
    projectId: 'weather-app-875f7',
    authDomain: 'weather-app-875f7.firebaseapp.com',
    storageBucket: 'weather-app-875f7.appspot.com',
    measurementId: 'G-S8LXTNKPT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3phsHRRbO643GOD-8R67GpKVmO73GMkQ',
    appId: '1:230882435362:android:57311c35715fdcc8b0c57b',
    messagingSenderId: '230882435362',
    projectId: 'weather-app-875f7',
    storageBucket: 'weather-app-875f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZUclToDyVn0Mjpk9Z1DM4M8w-URjKnaI',
    appId: '1:230882435362:ios:fb73d73babcfe1dcb0c57b',
    messagingSenderId: '230882435362',
    projectId: 'weather-app-875f7',
    storageBucket: 'weather-app-875f7.appspot.com',
    iosClientId: '230882435362-s3ffbt8u8mk9p0cvr9mol19b26bbg7g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZUclToDyVn0Mjpk9Z1DM4M8w-URjKnaI',
    appId: '1:230882435362:ios:fb73d73babcfe1dcb0c57b',
    messagingSenderId: '230882435362',
    projectId: 'weather-app-875f7',
    storageBucket: 'weather-app-875f7.appspot.com',
    iosClientId: '230882435362-s3ffbt8u8mk9p0cvr9mol19b26bbg7g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
